spring:
#  security.oauth2.resourceserver.jwt:
#    jwk-set-uri: http://${app.auth-server.host}:${app.auth-server.port}/.well-known/jwks.json
  # As Spring Cloud Ribbon is in maintenance mode.
  # It is recommended switching to BlockingLoadBalancerClient instead.
  cloud:
    # Route definitions of the system
    gateway:
      routes:
        - id: customer-service
          # lb:// is used to direct Spring Cloud Gateway to use the client-side load balancer
          # to look up the destination in the discovery service.
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

server:
  port: 8443 # SSL Port
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/test.p12
#    key-store-password: testtest
#    key-alias: localhost

logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
  org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
