spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:appusr}:${MONGO_PASSWORD:appdev}@${MONGO_HOST:localhost}:${MONGO_PORT:27018}/product-catalogue-db

server:
  port: 9065
