spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:carbonroot}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/customer-db

server:
  port: 9064

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    healthcheck.enabled: true
    service-url:
      defaultZone: "http://appusr:appdev@localhost:8761/eureka"
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
