server:
  port: 8833
  error:
    include-message: always
    include-binding-errors: always

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    healthcheck.enabled: true
    service-url:
      defaultZone: "http://appusr:appdev@localhost:8761/eureka"
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations:
            - ${app.config.path}/default
            - ${app.config.path}/edge
  security:
    user:
      name: appusr
      password: appdev
# WARNING: Exposing all management endpoints over http should only
#          be used during development, must be locked down in production!
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

app:
  config:
    path: "${APP_CONFIG_PATH:file:///D:/clean-architecture-engineering/order-management-microservice/config/files/}"
---
spring:
  profiles: docker
  cloud:
    config.server.native.searchLocations: file:/config/files