spring:
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092,localhost:29092,localhost:39092}

server:
  port: 9062

# to be replaced later on by feign client
app:
  customer-service:
    base-uri: ${CUSTOMER_SERVICE_URI:localhost:9064}
    customers-uri: ${app.customer-service.base-uri}/customers